# Generated by Django 6.0 on 2025-12-04 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante_api.categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante_api.produto'),
        ),
        migrations.AlterField(
            model_name='produtoingrediente',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante_api.produto'),
        ),
        migrations.DeleteModel(
            name='Prduto',
        ),
    ]
