# Generated by Django 5.2.8 on 2025-11-19 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtorDublador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Anime', 'ANIME'), ('Filme', 'FILME'), ('Serie', 'SERIE'), ('Livro', 'LIVRO')], max_length=5)),
                ('ano_lancamento', models.DateField(blank=True, null=True)),
                ('estudo_produtora', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('F', 'FEMININO'), ('M', 'MASCULINO'), ('O', 'OUTRO')], max_length=1)),
                ('especie', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('ator_dublador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_personagens.atordublador')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_personagens.obra')),
            ],
        ),
        migrations.CreateModel(
            name='PersonagemHabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_personagens.habilidade')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_personagens.personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Relacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacionamento', models.CharField(choices=[('RF', 'RELACIONAMENTO FAMILIAR'), ('RA', 'RELACIONAMENTO AMOROSO'), ('RAZ', 'RELACIONAMENTO DE AMIZADE'), ('RP', 'RELACIONAMENTO PROFISSIONAL')], max_length=3)),
                ('personagem1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personagem1', to='api_personagens.personagem')),
                ('personagem2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personagem2', to='api_personagens.personagem')),
            ],
        ),
    ]
